### ISSUE TITLE
Provide prebuilt library for s390x

### ISSUE THREAD

**Issue by AndrewFerr** [matrix-org/matrix-rust-sdk-crypto-nodejs#24]
See https://github.com/matrix-org/matrix-rust-sdk/issues/1503

**Comment by mgcm** [comment]
@AndrewFerr with the above PR now merged, it would be great if we could have a new release... any plans for that anytime soon?

thanks!

**Comment by Hywan** [comment]
Closing the issue, but I'll let @AndrewFerr do a new release.
